version: '3.8'

services:
  avis-microservice:
    container_name: avismicroservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://avis-db:5432/avis_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - avis-db
    networks:
      - shared-network

  avis-db:
    image: postgres:15
    container_name: avis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avis_db
    ports:
      - "5435:5432"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
